import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { DivaDig, DivaLogo } from "../components/DivaLogo";
import { getAllPosts, getAllSlugs } from './api/getPosts'

export type Post = {
  content: string,
  title: string,
  slug: string,
  date: string,
  excerpt: string,
}

export const getStaticProps = async () => {
  const posts = getAllPosts()

  return {
    props: {
      posts,
    },
  };
}

const Home: NextPage<{ posts: Post[] }> = ({ posts }) => {
  console.log(posts);
  return (
    <>
      <Head>
        <title>Diva Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className="moving-gradient">
        <figure className="h-4/5 flex flex-col justify-center items-center">
          <DivaDig className="mb-16 w-1/3" aria-label="Diva Protocol Logo" />
        </figure>
        <div className="flex text-1xl justify-center ">
          <h1 className="text-center mr-3">
            The future of derivatives is coming in 2022
          </h1>
          <ul className="flex">
            <li>
              <a
                className="text-blue mr-3 border-b pb-1"
                href="https://twitter.com/divaprotocol_io"
              >
                Twitter
              </a>
            </li>
            <li>
              <a
                className="text-blue mr-3 border-b pb-1"
                href="https://discord.gg/6xw3kEzc"
              >
                Discord
              </a>
            </li>
          </ul>
        </div>

        <ul>
          {posts.map((v) => (
            <li key={v.title}>
              <a href={`/posts/${v.slug}`}>{v.title}</a>
            </li>
          ))}
          <li>One blog post</li>
        </ul>
      </main>
    </>
  );
};

export default Home
