import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';
import { DivaLogo, DivaType } from "../components/DivaLogo";
import { format, parseISO } from 'date-fns';
import { ReadingIcon } from '../components/ReadingIcon';
import { getAllPosts, getAllSlugs } from './api/getPosts'

export type Post = {
  author: string;
  content: string;
  title: string;
  slug: string;
  date: string;
  coverImage: string;
  coverImageDescription: string;
  coverImageWidth: number;
  coverImageHeight: number;
  excerpt: string;
};

export const getStaticProps = async () => {
  const posts = getAllPosts();

  return {
    props: {
      posts: posts.map((v) => ({
        ...v,
        date: (v.date as unknown as Date).toISOString(),
      })),
    },
  };
};

const Home: NextPage<{ posts: Post[] }> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Diva Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main className="moving-gradient text-white overflow-auto">
        <div className="flex h-full flex-col">
          <figure className="h-full flex flex-col justify-center items-center">
            <DivaLogo
              className="stroke-text mb-16 w-40 max-w-xs"
              aria-label="Diva Protocol Logo"
            />
            <DivaType className="stroke-text w-80 fill-text" />
          </figure>
          <div className="text-center mr-3 flex align-center justify-center text-2xl text-text pt-3 pb-11 space-x-12">
            <p>The future of derivatives is here</p>
            <a
              className="mr-3 border-b pb-2"
              href="https://twitter.com/divaprotocol_io"
            >
              Twitter
            </a>

            <a
              className="mr-3 border-b pb-2"
              href="https://discord.gg/6xw3kEzc"
            >
              Discord
            </a>
          </div>
        </div>
        <div className="justify-center flex flex-col align-center space-y-20 pt-20 pb-44">
          <ReadingIcon className="w-8 self-center" />
          <ul className="self-center">
            {posts.map((v) => (
              <li key={v.title}>
                <a href={`/posts/${v.slug}`}  className="flex flex-col">
                  <span className="text-slate pb-3 text-center">
                    By <strong>{v.author}</strong> at{" "}
                    <time>{format(parseISO(v.date), "MMMM dd, yyyy")}</time>
                  </span>
                  <span className="text-2xl text-text">{v.title}</span>
                </a>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home
