import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/router'
import { Post } from '..';
import { DivaLogo } from '../../components/DivaLogo';
import Tweet from 'react-tweet-embed'
import { IMAGE_PATH } from '../../constants';
// @ts-ignore
import { getAllPosts, getPostBySlug } from '../api/getPosts';
import { MDXRemote, MDXRemoteSerializeResult } from 'next-mdx-remote';
import { GetStaticProps } from 'next';
import { serialize } from 'next-mdx-remote/serialize';
import { useEffect, useState } from 'react';
import { RandomVerticalSvgLine } from '../../components/RandomVerticalSvgLine';

export async function getStaticPaths() {
  const posts = getAllPosts()
  return {
    paths: posts.map((v) => ({
      params: { slug: v.slug },
    })),
    fallback: false,
  };
}

type PostPageProps = {
  source: MDXRemoteSerializeResult;
  post: Post;
};

const components = {
  Tweet,
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const post = getPostBySlug(params?.slug as string);

  const mdxSource = await serialize(post.content, {
   // Optionally pass remark/rehype plugins
    mdxOptions: {},
    scope: post,
  });

  console.log({ mdxSource });

  return {
    props: {
      source: mdxSource,
      post,
    },
  };
};

const PostPage = ({ source, post }: PostPageProps) => {

  return (
    <>
      <Head>
        <title>Diva Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <nav className="p-5 pl-10">
        <Link href="/" passHref>
          <a className="inline-block">
            <DivaLogo className="fill-text stroke-text h-8" />
          </a>
        </Link>
      </nav>
      <article className="pb-12 relative">
        <Image
          src={`${IMAGE_PATH}${post.coverImage}`}
          alt={post.coverImageDescription}
          width={post.coverImageWidth}
          height={post.coverImageHeight}
          layout="responsive"
        />
        <div className="pt-10 prose m-auto prose-slate">
          <h1>{post.title}</h1>
          <MDXRemote {...source} components={components} />
        </div>
      </article>
    </>
  );
};

export default PostPage